import uuid
from datetime import datetime
from sqlalchemy import String, func, JSON
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column
from app.db.database import Base


class User(Base):
    """
    SQLAlchemy model representing the 'users' table.
    Uses modern Type-Annotated Declarative Mapping (Mapped/mapped_column) for SQLAlchemy 2.0.
    """
    __tablename__ = "users"

    # UUID primary key generated at DB level (fallback to Python uuid4 on creation)
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    # Email field, indexed and enforced unique
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )

    # Hashed password (nullable for OAuth users)
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=True,
    )

    # Google ID for OAuth
    google_id: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=True,
        index=True,
    )

    # Auto-populated created timestamp using PostgreSQL's server time
    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<User {self.email}>"


class RepositorySummary(Base):
    """
    SQLAlchemy model representing the 'repository_summaries' table.
    Stores high-level architecture and metadata summaries generated by the LLM.
    """
    __tablename__ = "repository_summaries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=func.gen_random_uuid(),
    )

    repo_url: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
    )

    summary_json: Mapped[dict] = mapped_column(
        JSON,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<RepositorySummary {self.repo_url}>"
