import logging
import os
import uuid
from typing import Any, Dict, List

from qdrant_client import QdrantClient, models
from qdrant_client.http.exceptions import UnexpectedResponse

# Configure logger for tracking database operations
logger = logging.getLogger(__name__)

class VectorDBClient:
    """
    A robust, production-ready client to interact with the Qdrant vector database.
    Handles secure connections, automated collection management, batch insertion of 
    embedded code chunks, and fast semantic retrieval operations.
    """
    
    def __init__(self, collection_name: str = "codebase_chunks", vector_size: int = 1536):
        """
        Initializes the Qdrant client connection and ensures the target collection exists.
        
        :param collection_name: Name of the collection to store codebase vectors.
        :param vector_size: Size of the embedding vectors (1536 is standard for OpenAI text-embedding-3-small).
        """
        self.collection_name = collection_name
        self.vector_size = vector_size
        
        # Load connection settings from the environment with sensible fallbacks
        qdrant_host = os.getenv("QDRANT_HOST", "localhost")
        qdrant_port = int(os.getenv("QDRANT_PORT", "6333"))
        
        try:
            # Initialize the Qdrant client. 
            self.client = QdrantClient(host=qdrant_host, port=qdrant_port)
            self._ensure_collection_exists()
        except Exception as e:
            logger.error(f"Failed to connect to Qdrant at {qdrant_host}:{qdrant_port} - {e}")
            raise RuntimeError(f"Vector database connection failed: {e}")

    def _ensure_collection_exists(self):
        """
        Validates if the target collection exists in Qdrant.
        If it doesn't, it provisions it automatically using Cosine distance configuration.
        """
        try:
            # Fetch all existing collections from the database
            collections_response = self.client.get_collections()
            collection_names = [col.name for col in collections_response.collections]
            
            # Create collection if absent
            if self.collection_name not in collection_names:
                logger.info(f"Collection '{self.collection_name}' not found. Provisioning it now...")
                
                self.client.create_collection(
                    collection_name=self.collection_name,
                    vectors_config=models.VectorParams(
                        size=self.vector_size,
                        distance=models.Distance.COSINE
                    ),
                )
                logger.info(f"Successfully created collection: {self.collection_name}")
        except UnexpectedResponse as e:
            logger.error(f"Error checking or creating Qdrant collection: {e}")
            raise

    def store_chunks(self, chunks: List[Dict[str, Any]], embeddings: List[List[float]]):
        """
        Stores parsed code chunks and their corresponding embeddings into the vector database.
        
        :param chunks: List of chunk metadata dictionaries (must include file_path, chunk_type, name, content, etc.)
        :param embeddings: List of float vectors generated by the embedder. Must correspond 1:1 with chunks.
        """
        if len(chunks) != len(embeddings):
            raise ValueError(f"Mismatch: Received {len(chunks)} chunks but {len(embeddings)} embeddings.")
            
        if not chunks:
            logger.warning("No chunks provided to store. Skipping ingestion.")
            return

        points = []
        # Zip pairs the chunk metadata with its corresponding vector array
        for chunk, embedding in zip(chunks, embeddings):
            # Qdrant requires a unique UUID string or integer for every point
            point_id = str(uuid.uuid4())
            
            # Package the metadata to be stored alongside the vector.
            # This is critical for RAG, as this payload is what gets returned during a search.
            payload = {
                "file_path": chunk.get("file_path", "unknown"),
                "chunk_type": chunk.get("chunk_type", "unknown"),
                "name": chunk.get("name", "unknown"),
                "content": chunk.get("content", ""),
                "start_line": chunk.get("start_line", 0),
                "end_line": chunk.get("end_line", 0)
            }
            
            # Construct the point object
            point = models.PointStruct(
                id=point_id,
                vector=embedding,
                payload=payload
            )
            points.append(point)

        try:
            # Upsert inserts new points or updates existing ones with the same ID.
            # Note: For massive codebases (>10k chunks), consider chunking the `points` array
            # into smaller batches (e.g., 500 at a time) to prevent network timeouts.
            self.client.upsert(
                collection_name=self.collection_name,
                points=points
            )
            logger.info(f"Successfully upserted {len(points)} chunks into {self.collection_name}")
        except Exception as e:
            logger.error(f"Failed to upsert points into Qdrant: {e}")
            raise RuntimeError(f"Database insertion failed: {e}")

    def search_similar(self, query_embedding: List[float], top_k: int = 5) -> List[Dict[str, Any]]:
        """
        Searches the vector database for the codebase chunks most semantically similar 
        to the provided query embedding.
        
        :param query_embedding: The dense vector representing the user's search query.
        :param top_k: The number of highest-scoring results to return (default: 5).
        :return: A list of dictionaries containing the similarity score and the chunk payload.
        """
        try:
            # Perform the Approximate Nearest Neighbor (ANN) search using the new query_points API
            search_results = self.client.query_points(
                collection_name=self.collection_name,
                query=query_embedding,
                limit=top_k,
                with_payload=True  # We need the payload back to feed to the LLM
            )
            
            # Format the raw Qdrant response into clean, easily readable dictionaries
            formatted_results = []
            for result in search_results.points:
                formatted_results.append({
                    "score": result.score, # The Cosine similarity score (closer to 1.0 is better)
                    "payload": result.payload
                })
                
            return formatted_results
        except Exception as e:
            logger.error(f"Semantic search failed in Qdrant: {e}")
            raise RuntimeError(f"Database search failed: {e}")
